---

- name: Import mariadb repository key
  apt_key: keyserver=keyserver.ubuntu.com id={{item}}
  with_items:
    - "0xcbcb082a1bb943db"
    - "0xF1656F24C74CD1D8"
  notify: update apt
  when: ansible_os_family == 'Debian'
  tags:
    - apt_key

- name: Configure software repository (debian/ubuntu)
  template: src=mariadb.list.j2 dest=/etc/apt/sources.list.d/mariadb.list
  notify: update apt
  when: ansible_os_family == 'Debian'
  tags:
    - apt_repo

- name: Configure software repository (centos/redhat)
  template: src=mariadb.repo.j2 dest=/etc/yum.repos.d/mariadb.repo
  when: ansible_os_family == 'RedHat'
  tags:
    - yum_repo

- name: Flush handlers
  meta: flush_handlers

- name: delete mysql default location {{ mysql_std_path }} if exists
  file:
    path: "{{ mysql_std_path }}"
    state: absent
  failed_when: False
  when: mysql_mount is defined and mysql_mount is is_mount and not mysql_std_path is is_link

- name: create symlink target directory at mountpoint {{ mysql_mount }}
  file:
    path: "{{ mysql_mount }}/mysql"
    state: directory
  register: mysql_symlink
  when: mysql_mount is defined and mysql_mount is is_mount

- name: create symlink {{ mysql_mount }}/mysql to mountpoint {{ mysql_std_path }}
  file:
    src: "{{ mysql_mount }}/mysql"
    dest: "{{ mysql_std_path }}"
    state: link
  when: mysql_mount is defined and mysql_mount is is_mount and not mysql_std_path is is_link

## permission is 0660 for user mysql:mysql but user mysql only exists after packet installation. So we need a temporary permission with access for everyone as dirty hack
- name: change permissions for newly created directory
  file:
    path: "{{ mysql_mount }}/mysql"
    state: directory
    mode: '0777'
  register: mysql_symlink
  when: mysql_symlink.changed

- name: Install MariaDB Server (debian/ubuntu)
  package:
    name: "{{ mariadb_apt_packages | from_yaml }}"
    state: present
  when: ansible_os_family == 'Debian'
  tags:
    - apt_pkg

- name: Install MariaDB Server (centos/redhat)
  package:
    name: "{{ mariadb_yum_packages | from_yaml }}"
    state: present
  when: ansible_os_family == 'RedHat'
  tags:
    - yum_pkg

- name: set symlink destination permissions
  file:
    path: "{{ mysql_mount }}/mysql"
    state: directory
    owner: mysql
    group: mysql
    mode: '0770'
    recurse: yes
  when: mysql_mount is defined and mysql_mount is is_mount

- name: Create config files
  include: configuration.yml
  
- name: Template misc mariadb config files
  template: src="{{item.src}}" dest="{{item.dest}}" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0600')}}"
  with_items: "{{ mariadb_misc_config_files | from_yaml }}"
  tags:
    - ssl_cnf
    - mysql-tuning
    - template
  register: misc_config_changed

- name: configuration has changed
  shell: echo register variable
  register: mysql_config_changed
  when: file_custom_vars_changed.changed or file_mysql_config_changed.changed or
        file_mysqldump_config_changed.changed or file_mysqld_config_changed.changed or
        file_mysqld_safe_config_changed.changed or file_galera_config_changed.changed

- name: Template mariadb nrpe config
  template: src="{{item.src}}" dest="{{item.dest}}" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0600')}}"
  with_items:
    - { src: "nrpe-mariadb.cfg.j2", dest: "{{nrpe_include_dir}}/role-mariadb.cfg", owner: "nrpe", group: "nrpe", mode: "0440" }
  when: mariadb_nrpe|bool
  tags:
    - nrpe

- name: Template instance-configurations
  template: src="mariadb_instance.j2" dest="{{mariadb_conf_dir}}/instance_{{item.name}}.cnf" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0644')}}"
  with_flattened:
    - "{{mariadb_instances}}"
  when: mariadb_multiple_instances|bool
  tags:
    - template

- name: Create backup directory
  file: state=directory path="{{mariadb_backup_root}}"
  when: mariadb_configure_xtrabackup|bool or mariadb_configure_backupninja|bool

- include_tasks: "mydumper.yml"
  when: mariadb_install_mydumper_binary|bool or mariadb_install_mydumper_package|bool

- include_tasks: "backupninja.yml"
  when: mariadb_configure_backupninja|bool

- include_tasks: "xtrabackup.yml"
  when: mariadb_configure_xtrabackup|bool

- name: Template ufw config for galera/mysql (ubuntu)
  template: src="{{item.src}}" dest="{{item.dest}}" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0600')}}"
  with_items:
    - { src: "ufw-galera.j2", dest: "/etc/ufw/applications.d/galera", mode: "0644" }
  when: ansible_os_family == 'Debian'
  tags:
    - firewall
    - template

- name: Template firewalld config for galera/mysql (centos/redhat)
  template: src="{{item.src}}" dest="{{item.dest}}" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0600')}}"
  with_items:
    - { src: "firewalld-galera.j2", dest: "/etc/firewalld/services/galera.xml", mode: "0644" }
  when: ansible_os_family == 'RedHat'
  tags:
    - firewall
    - template

- name: Allow galera cluster to communicate 1 (ubuntu)
  ufw: rule=allow name="galera" src="{{item}}/32"
  with_items:
    - "{{galera_cluster_nodes}}"
  when: ansible_os_family == 'Debian' and ufw_enabled|bool
  tags:
    - firewall

- name: Allow galera cluster to communicate 2 (ubuntu)
  ufw: rule=allow name="galera-udp" src="{{item}}/32"
  with_items:
    - "{{galera_cluster_nodes}}"
  when: ansible_os_family == 'Debian' and ufw_enabled|bool
  tags:
    - firewall

- name: Allow galera cluster to communicate (redhat)
  firewalld: service="galera" permanent=true state=enabled immediate=true
  when: ansible_os_family == 'RedHat' and firewalld_enabled|bool
  tags:
    - firewall

- name: Add Galera ports to mysqld_port_t selinux tag
  seport: ports="{{item.port}}" proto="{{item.proto|default('tcp')}}" setype="{{item.setype}}" state="{{item.state|default('present')}}"
  with_items:
    - { port: "4444", setype: "mysqld_port_t" }
    - { port: "4567", setype: "mysqld_port_t" }
    - { port: "4568", setype: "mysqld_port_t" }
    - { port: "4567", setype: "mysqld_port_t", proto: "udp" }
  when: ansible_os_family == 'RedHat' and ansible_selinux.status == 'enabled'
  tags:
    - selinux
    - seport

- name: Set selinux permissive mode for mysqld_t
  selinux_permissive: name=mysqld_t permissive=true
  when: ansible_os_family == 'RedHat' and ansible_selinux.status == 'enabled'
  tags:
    - selinux
    - sepermissive

- name: Check if MariaDB is running
  shell: ps aux | grep mysql | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: service_mysql_status

- name: get database quorum size ( (cluster number of incoming addresses / 2) +1 )
  shell: "echo $((($(mysql <<< \"SHOW STATUS LIKE 'wsrep_incoming_addresses';\" | awk '{print $2}' | tail -n 1 | sed \"s/,/ /\"g |wc -w)/2)+1))"
  args: 
    executable: /bin/bash
  register: galera_quorum_size
  changed_when: false
  when: service_mysql_status.rc == 0

- name: get database cluster status for this node
  shell: "mysql <<< \"SHOW STATUS LIKE 'wsrep_cluster_status';\" | awk '{print $2}'| tail -n 1"
  args: 
    executable: /bin/bash
  register: galera_wsrep_cluster_status
  changed_when: false
  when: service_mysql_status.rc == 0

- name: get database cluster size for this node
  shell: "mysql <<< \"SHOW STATUS LIKE 'wsrep_cluster_size';\" | awk '{print $2}'| tail -n 1"
  args: 
    executable: /bin/bash
  register: galera_wsrep_cluster_size
  changed_when: false
  when: service_mysql_status.rc == 0

- debug:
    msg: galera_wsrep_cluster_status={{ galera_wsrep_cluster_status }} galera_wsrep_cluster_size={{ galera_wsrep_cluster_size }}
  when: debug is defined and (debug|bool)
        and service_mysql_status.rc == 0

- debug:
    msg: galera_wsrep_cluster_status={{ galera_wsrep_cluster_status }} galera_wsrep_cluster_size={{ galera_wsrep_cluster_size }} galera_quorum_size={{ galera_quorum_size }}
  when: debug is defined and (debug|bool)

- name: stop mariadb if config changed (warning! this can take from one second to several hours according to your cluster)
  service: name=mariadb state=stopped
  when: mysql_config_changed.changed and
        service_mysql_status.rc == 0 and
        galera_wsrep_cluster_status.stdout|lower == "primary" and galera_wsrep_cluster_size.stdout|int > galera_quorum_size.stdout|int

- name: test if first node does normal start
  service:  name=mariadb state=started
  when: 
        ((galera_current_node_name is defined and galera_current_node_name == (galera_cluster_nodes|from_yaml)[0] ) or
        ( ansible_hostname == (galera_cluster_nodes|from_yaml)[0] )) and
        mysql_config_changed.changed
  register: firstnode_start_test
  ignore_errors: true

- debug: 
    msg: |
         firstnode_start_test={{ firstnode_start_test }} 
         galera_cluster_nodes[0]={{ (galera_cluster_nodes| from_yaml)[0] }}
         mysql_config_changed.changed={{ mysql_config_changed.changed }}
         galera_current_node_name={{ galera_current_node_name }}
  when: debug is defined and (debug|bool)

- name: test if first node does initial start
  command: "/usr/bin/galera_new_cluster"
  become: true
  when: 
        ((galera_current_node_name is defined and galera_current_node_name == (galera_cluster_nodes|from_yaml)[0] ) or
        ( ansible_hostname == (galera_cluster_nodes|from_yaml)[0] )) and
        mysql_config_changed.changed and
        (firstnode_start_test.failed|bool)
  ignore_errors: true
  register: firstnode_initial_start_test

- name: start non_initial nodes
  service:  name=mariadb state=started
  when:
        ((galera_current_node_name is defined and galera_current_node_name != (galera_cluster_nodes|from_yaml)[0] ) or
        ( ansible_hostname != (galera_cluster_nodes|from_yaml)[0] )) and
        mysql_config_changed.changed

