---

- name: Import mariadb repository key
  apt_key: keyserver=keyserver.ubuntu.com id={{item}}
  with_items:
    - "0xcbcb082a1bb943db"
    - "0xF1656F24C74CD1D8"
  notify: update apt
  when: ansible_os_family == 'Debian'
  tags:
    - apt_key

- name: Configure software repository (debian/ubuntu)
  template: src=mariadb.list.j2 dest=/etc/apt/sources.list.d/mariadb.list
  notify: update apt
  when: ansible_os_family == 'Debian'
  tags:
    - apt_repo

- name: Configure software repository (centos/redhat)
  template: src=mariadb.repo.j2 dest=/etc/yum.repos.d/mariadb.repo
  when: ansible_os_family == 'RedHat'
  tags:
    - yum_repo

- name: Flush handlers
  meta: flush_handlers

- name: Install MariaDB Server (debian/ubuntu)
  apt: name={{item}} state=installed
  with_items:
    - mariadb-server-{{mariadb_version}}
    - mariadb-client-core-{{mariadb_version}}
    - galera-3
  when: ansible_os_family == 'Debian'
  tags:
    - apt_pkg

- name: Install MariaDB Server (centos/redhat)
  yum: name={{item}} state=installed
  with_items:
    - mariadb-server
    - mariadb
    - galera
  when: ansible_os_family == 'RedHat'
  tags:
    - yum_pkg

- name: Template galera config file (when in a galera cluster)
  template: src="{{item.src}}" dest="{{item.dest}}" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0600')}}"
  with_items:
    - { src: "galera.cnf.j2", dest: "{{mariadb_conf_dir}}/galera.cnf", mode: "0644" }
  when: galera_wsrep_cluster_name != ""
  tags:
    - galera
    - template

- name: Template misc mariadb config files
  template: src="{{item.src}}" dest="{{item.dest}}" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0600')}}"
  with_items:
    - { src: "ssl.cnf.j2", dest: "{{mariadb_conf_dir}}/ssl", mode: "0644" }
    - { src: "tuning.cnf.j2", dest: "{{mariadb_conf_dir}}/tuning.cnf", mode: "0644" }
    - { src: "mariadb@.service", dest: "/etc/systemd/system/mariadb@.service" }
  tags:
    - ssl_cnf
    - mysql-tuning
    - template

- name: Template instance-configurations
  template: src="mariadb_instance.j2" dest="{{mariadb_conf_dir}}/instance_{{item.name}}.cnf" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0600')}}"
  with_flattened:
    - "{{mariadb_instances}}"
  when: mariadb_multiple_instances|bool
  tags:
    - template

- name: Template ufw config for galera/mysql (ubuntu)
  template: src="{{item.src}}" dest="{{item.dest}}" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0600')}}"
  with_items:
    - { src: "ufw-galera.j2", dest: "/etc/ufw/applications.d/galera", mode: "0644" }
  when: ansible_os_family == 'Debian'
  tags:
    - firewall
    - template

- name: Template firewalld config for galera/mysql (centos/redhat)
  template: src="{{item.src}}" dest="{{item.dest}}" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.mode|default('0600')}}"
  with_items:
    - { src: "firewalld-galera.j2", dest: "/etc/firewalld/services/galera.xml", mode: "0644" }
  when: ansible_os_family == 'RedHat'
  tags:
    - firewall
    - template

- name: Allow galera cluster to communicate 1 (ubuntu)
  ufw: rule=allow name="galera" src="{{item}}/32"
  with_items:
    - "{{galera_cluster_nodes}}"
  when: ansible_os_family == 'Debian' and ufw_enabled|bool
  tags:
    - firewall

- name: Allow galera cluster to communicate 2 (ubuntu)
  ufw: rule=allow name="galera-udp" src="{{item}}/32"
  with_items:
    - "{{galera_cluster_nodes}}"
  when: ansible_os_family == 'Debian' and ufw_enabled|bool
  tags:
    - firewall

- name: Allow galera cluster to communicate (redhat)
  firewalld: service="galera" permanent=true state=enabled immediate=true
  when: ansible_os_family == 'RedHat' and firewalld_enabled|bool
  tags:
    - firewall

- name: Add Galera ports to mysqld_port_t selinux tag
  seport: ports="{{item.port}}" proto="{{item.proto|default('tcp')}}" setype="{{item.setype}}" state="{{item.state|default('present')}}"
  with_items:
    - { port: "4444", setype: "mysqld_port_t" }
    - { port: "4567", setype: "mysqld_port_t" }
    - { port: "4568", setype: "mysqld_port_t" }
    - { port: "4567", setype: "mysqld_port_t", proto: "udp" }
  when: ansible_os_family == 'RedHat' and ansible_selinux.status == 'enabled'
  tags:
    - selinux
    - seport

- name: Set selinux permissive mode for mysqld_t
  selinux_permissive: name=mysqld_t permissive=true
  when: ansible_os_family == 'RedHat' and ansible_selinux.status == 'enabled'
  tags:
    - selinux
    - sepermissive
